apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce               
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        readinessProbe:
          exec:
            command:
                - mysqladmin
                - ping
                - -h
                - localhost
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pass"
        - name: MYSQL_DATABASE
          value: "db"
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-provide
      volumes:
        - name: mysql-provide
          persistentVolumeClaim:
            claimName: pvc-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: user-app-api
        image: surtaev/user-app-api:latest
        env:
          - name: FLASK_APP
            value: app.py
          - name: FLASK_ENV
            value: development
          - name: SQLALCHEMY_DATABASE_URI
            value: mysql+mysqlconnector://root:pass@mysql/db
        ports:
        - containerPort: 5000
        volumeMounts:
            - name: templates
              mountPath: /templates
            - name: static
              mountPath: /static
      volumes:
        - name: templates
          hostPath:
            path: /user-app/app.py
        - name: static
          hostPath:
            path: /user-app/static
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  selector:
    matchLabels:
      app: adminer
  replicas: 1
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
spec:
  selector:
    app: adminer
  ports:
  - port: 8080
    targetPort: 8080