name: CI/CD for K8S
on: push
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Check code
              uses: actions/checkout@v4
            - name: Setup buildx Docker
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                    username: surtaev
                    password: ${{secrets.DOCKER_TOKEN}}
            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: |
                    surtaev/user-app-api:latest
                    surtaev/user-app-api:${{ github.sha }}
            - name: install K8S
              uses: azure/setup-kubectl@v4
            - name: Deploy
              run: kubectl apply -f deploy.yaml
               