name: Test
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
          SQLALCHEMY_DATABASE_URI: mysql+mysqlconnector://root:pass@db/db
        services:
          mysql:
            image: mysql:8.0
            env:
                MYSQL_ROOT_PASSWORD: pass
                MYSQL_DATABASE: db
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: verifa sql connect
              run: mysql --host=127.0.0.1 --port=3306 --user=root --password=pass -e "SHOW DATABASES;
            - name: Install PYTHON
              uses: actions/setup-python@v5
              with:
                python-version: '3.10.11'
                cache: 'pip'
            - name: Install dependencies
              run: pip install --no-cache-dir -r requirements.txt
            - name: run Test
              run: python app.py


            
          


         
              