name: Test
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
          SQLALCHEMY_DATABASE_URI: mysql+mysqlconnector://root:pass@db/db
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install Mysql
              run: | 
                sudo apt-get update 
                sudo apt-get install -y mysql-server
                sudo systemctl start mysql 
            - name: Configure MYSQL
              run: |
                sudo mysql
                sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'pass';"
                sudo mysql -u root -ppass -e "CREATE DATABASE db;"
                sudo mysql -u root -ppass -e "FLUSH PRIVILEGES;"
            - name: Install PYTHON
              uses: actions/setup-python@v5
              with:
                python-version: '3.10.11'
                cache: 'pip'
            - name: Install dependencies
              run: pip install --no-cache-dir -r requirements.txt
            - name: run Test
              run: python app.py


            
          


         
              