name: Test
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
          SQLALCHEMY_DATABASE_URI: mysql+mysqlconnector://root:pass@db/db
        services:
          mysql:
            image: mysql:8.0
            env:
                MYSQL_ROOT_PASSWORD: pass
                MYSQL_DATABASE: db
            options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=5s --health-retries=10
            ports:
              - 3306:3306
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: install client mysql
              run: |
                sudo apt-get update && sudo apt install -y default-mysql-client 
            - name: Wait for MySQL to be ready
              run: |
                mysql --host=127.0.0.1 \
                --port=3306 \
                --user=root \
                --password=pass \
                -e "SELECT VERSION();" 
            - name: Verify DB connection and setup
              run: |
                mysql --host=127.0.0.1 \
                --port=3306 \
                --user=root \
                --password=pass \
                -e "SHOW DATABASES;" 
                
                mysql --host=127.0.0.1 \
                --port=3306 \
                --user=root \
                --password=pass \
                -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'pass'; FLUSH PRIVILEGES;"
                
            - name: Install PYTHON
              uses: actions/setup-python@v5
              with:
                python-version: '3.10.11'
                cache: 'pip'
            - name: Install dependencies
              run: pip install --no-cache-dir -r requirements.txt
            - name: run Test
              run: python app.py


            
          


         
              