name: Test
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        env:
          FLASK_APP: app.py
          FLASK_ENV: development
          SQLALCHEMY_DATABASE_URI: mysql+mysqlconnector://root:pass@db/db
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install Mysql
              run: | 
                sudo apt-get update 
                sudo apt-get install -y mysql-server
                sudo systemctl start mysql  
            - name: Install PYTHON
              uses: actions/setup-python@v5
              with:
                python-version: '3.10.11'
                cache: 'pip'
            - name: Install dependencies
              run: pip install --no-cache-dir -r requirements.txt
            - name: Wait for MySQL
              run: |
                until mysqladmin ping -h 127.0.0.1; do
                  echo "Waiting for MySQL..."
                  sleep 2
                done
            - name: run Test
              run: python app.py


            
          


         
              